codecov:
  require_ci_to_pass: true
  # token: ${{ secrets.CODECOV_TOKEN }} -> Not necessary in public repos

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: true
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
