# Development mode

version: "3.7"

services:
  app:
    build: .
    image: marcelo-munhoz_img
    volumes:
      - .:/marcelo-munhoz
    working_dir: /marcelo-munhoz
    container_name: "marcelo-munhoz_ctn"
    hostname: "marcelo-munhoz"
    ports:
      - 4242:4242
    entrypoint: ["nuxt"]
