# for local development
services:
  app:
    image: marcelo-munhoz_img
    build:
      context: .
      target: "develop"
    ports:
      - "4242:4242"  # Frontend Quasar (dev)
      - "3000:3000"  # Backend Express
    volumes:
      - ./app:/app
    container_name: "marcelo-munhoz_ctn"
    env_file:
      - ./app/.env
    environment:
      - NODE_ENV=development
    command: /bin/sh -c "npm i && npm run dev"
    # entrypoint: [ "sh", "-c", "sleep 2073600" ]
