# for local development
version: "3.7"
services:
  app:
    image: marcelo-munhoz_img
    build:
      context: .
      target: "develop"
    ports:
      - "4242:4242"
    volumes:
      - ".:/app"
    container_name: "marcelo-munhoz_ctn"
    command: /bin/sh -c "npm i && npm run dev"
    # entrypoint: [ "sh", "-c", "sleep 2073600" ]
