name: marcelo-munhoz-tests

services:
  test:
    profiles: [test]
    image: marcelo-munhoz-tests-test
    build:
      context: .
      target: test-runtime
    command: [npm, test]
    init: true
    networks: [test-network]

  test-frontend:
    profiles: [e2e, chrome, firefox]
    image: marcelo-munhoz-tests-test
    build:
      context: .
      target: test-runtime
    command: [npm, run, dev, --, --host, 0.0.0.0]
    expose: ["1991"]
    init: true
    networks: [test-network]

  test-backend:
    profiles: [e2e, chrome, firefox]
    image: marcelo-munhoz-tests-test
    build:
      context: .
      target: test-runtime
    command: [node, middleware/server.js]
    expose: ["3000"]
    init: true
    networks: [test-network]

  cypress-chrome:
    profiles: [chrome]
    build:
      context: .
      target: test-browser-runtime
    command: [npx, cypress, run, --browser, chrome]
    depends_on:
      test-frontend:
        condition: service_started
      test-backend:
        condition: service_started
    init: true
    networks: [test-network]

  cypress-firefox:
    profiles: [firefox]
    build:
      context: .
      target: test-browser-runtime
    command: [npx, cypress, run, --browser, firefox]
    depends_on:
      test-frontend:
        condition: service_started
      test-backend:
        condition: service_started
    init: true
    networks: [test-network]

networks:
  test-network:
    internal: true
