# Development mode

version: "3.7"

services:
  app:
    build: .
    image: marcelo-munhoz_img
    volumes:
      - .:/app
    working_dir: /app
    container_name: "marcelo-munhoz_ctn"
    hostname: "marcelo-munhoz"
    ports:
      - 4242:4242
    entrypoint: ["nuxt"]
    # entrypoint: ["sh", "-c", "sleep 2073600"] for debug
