# for production
services:
  app:
    image: marcelo-munhoz_prod_img
    build:
      context: .
      target: "production"
    ports:
      - "3000:3000"
    volumes:
      - "./app:/app"
    container_name: "marcelo-munhoz_prod_ctn"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    # entrypoint: [ "sh", "-c", "sleep 2073600" ]
