[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https:; script-src 'self' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://en.gravatar.com/userimage/612044/*  https://res.cloudinary.com/marcelo-munhoz/image/* https://raw.githubusercontent.com/MarcMunhoz/*;"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=15552000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
