[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src https:; connect-src 'self' https://identity.netlify.com https://media-editor.cloudinary.com https://res.cloudinary.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://identity.netlify.com https://media-editor.cloudinary.com; frame-src 'self' https://media-editor.cloudinary.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://res.cloudinary.com https://en.gravatar.com https://cdn.jsdelivr.net;"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=15552000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "CLOUDINARY_UPLOAD_FOLDER,CLOUDINARY_FOLDER"

[[redirects]]
  from = "/api/admin/contentful/*"
  to = "/.netlify/functions/contentful-admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/contentful/*"
  to = "/.netlify/functions/contentful/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
