---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: "${{ secrets.NETLIFY_WEBHOOK }}"
sections:
- type: directory
  path: content/articles
  label: Blog
  create: documents
  match: "*"
  templates:
  - article
upload_dir: ''
public_path: https://res.cloudinary.com/marcelo-munhoz/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm i
  preview_docker_image: node:14-alpine
  mount_path: "/srv"
  working_dir: "/srv/app"
  instant_preview_command: nuxt
